### ISSUE TITLE
Wasm Issue in Vercel deployment with tiny-secp256k1

### ISSUE THREAD

**Issue by thebrandonlucas** [alexbosworth/lightning#120]
Hello, I'm using this package in an ExpressJS application and everything is working fine locally, and when I try to deploy the app to Vercel, it builds fine, but when I try to hit any endpoint the "Serverless function" API crashes. It appears to be some issue with WASM in the `tiny-secp256k1` library:

```[GET] /
22:05:49:43
2022-12-28T03:05:49.932Z	undefined	ERROR	Error: ENOENT: no such file or directory, open '/var/task/node_modules/tiny-secp256k1/lib/secp256k1.wasm'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at Object.<anonymous> (/var/task/node_modules/tiny-secp256k1/lib/cjs/wasm_loader.cjs:7:38)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/var/task/node_modules/tiny-secp256k1/lib/cjs/index.cjs:6:26) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/task/node_modules/tiny-secp256k1/lib/secp256k1.wasm'
}
RequestId: df756a57-dcb4-4030-bc3f-161f656813fd Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I tried setting the resolution to a different version of the library that I think predates the use of wasm:

```
"resolutions": {
    "tiny-secp256k1": "1.1.6"
  }
```

but am not sure how to tell if the different resolution is taking effect in the deployment, and still am not sure why this would work for me locally but not in a vercel deployment.

Another interesting thing is that I'm using this as a monorepo with two separate projects (the `ui` folder is Sveltekit and `api` is ExpressJS. Both of them use this dependency, but only the ExpressJS is failing when trying to hit an API endpoint. Here is the code: https://github.com/thebrandonlucas/video-lsat

Any help here would be appreciated, thanks!

**Comment by alexbosworth** [comment]
probably it is specific to vercel like if they try to figure out dependencies and they don't pick up the wasm

**Comment by bkiac** [comment]
I agree with @alexbosworth that this is unrelated to the lightning package

We run into the same problem at Hoseki, we decided to inline the wasm binary as a base64 string with [`patch-package`](https://github.com/ds300/patch-package), then update the import method to read the binary from the base64 string instead of the file. Although it's quite ugly, I'm not sure what else can be done on the consumer side, let me know if you find a better solution.

```ts
// node_modules/tiny-secp256k1/lib/secp256k1-wasm.ts
// inline the binary
const base64Binary = "..."
// then replace this line
const mod = new WebAssembly.Module(binary);
// with this
const mod = new WebAssembly.Module(Buffer.from(base64Binary, 'base64'));
```

**Comment by thebrandonlucas** [comment]
Thanks for the help! I was able to solve this by deploying using the vercel CLI and the `vercel deploy` command. If I understand correctly, it's deploying with the dependencies I have locally, and since that WASM file exists locally it's getting pushed with the deploy. Really good to know about `patch-package` though.

Closing this issue for now.

**Comment by dylanbathurst** [comment]
@bkiac I tried your solution but no luck. When I converted the wasm file to base64 it was so long that the application just seemed to throw during the `Buffer.from(...)` part. Could you share the base64 of the file that you used successfully?

**Comment by bkiac** [comment]
@dylanbathurst We ended up copying the wasm file to the build and adjusting the import path in `tiny-secp256k1` with [`patch-package`](https://www.npmjs.com/package/patch-package), this is in an Electron environment with `tiny-secp256k1@2.2.1` so your solution will probably be different. This is how we did it:

1. Adjust the import path in the module, here is our patch file
```
diff --git a/node_modules/tiny-secp256k1/lib/wasm_path.js b/node_modules/tiny-secp256k1/lib/wasm_path.js
index d45b843..d32b5f3 100644
--- a/node_modules/tiny-secp256k1/lib/wasm_path.js
+++ b/node_modules/tiny-secp256k1/lib/wasm_path.js
@@ -1,5 +1,4 @@
-import { URL, fileURLToPath } from "url";
 export function path(wasmFilename) {
-    const url = new URL(wasmFilename, import.meta.url);
-    return fileURLToPath(url);
+    const path = require('path').join(__dirname, `${wasmFilename}`);
+    return path;
 }
```
2. Copy `node_modules/tiny-secp256k1/lib/secp256k1.wasm` file to root `static` folder

[For Vercel/Next.js you'll probably need to copy the wasm file to your build similar to the proto files](https://github.com/alexbosworth/lightning/issues/48#issuecomment-1661586683) and update the import path in the first step so the library can read it

Our previous solution was to create a JS file that exports the inline binary in base64 format and then use this to create the WebAssembly module. [Here is the patch file for this solution.](https://gist.github.com/bkiac/cd2b510ac989f731c826db25aac6903d) Note that this creates a `.ts` file instead of `.js`, you may want to create a JS file instead of TS if your environment doesn't transpile `node_modules`.
